name: "Code scan the app"

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SONAR_PROJECT_KEY:
        required: true
      SONAR_ORG:
        required: true


jobs:
  code_scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SonarCloud Scanner
      uses: sonarsource/sonarqube-scan-action@v2.3.0
      with:
        args: >
          sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} sonar.organization=${{ secrets.SONAR_ORG }} sonar.host.url=${{ secrets.SONAR_HOST_URL }} sonar.login=${{ secrets.SONAR_TOKEN }} #magic___^_^___line #magic___^_^___line
