name: "Trivy Container Scan"

on:
  workflow_call:

jobs:
  docker-scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t verdant-sphere-user-service-api:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      id: trivy-scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 'verdant-sphere-user-service-api:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Debug SARIF file
      run: cat trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: trivy-results.sarif
