name: 'Dockernize the app'

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image And Push
      run: |
        docker build -t verdant-sphere-user-service-api .

    - name: Tag Docker image
      run: |
        docker tag verdant-sphere-user-service-api ${{ secrets.DOCKERHUB_USERNAME }}/verdant-sphere-user-service-api:latest

    - name: Push To Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/verdant-sphere-user-service-api:latest


