name: "Test the app"

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

jobs:
  test:
    name: Test the app
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
        - 27017:27017
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore Node module
      id: node-module-cache
      uses: actions/cache@v4.0.2
      with:
        key: ${{ github.sha }}-node-modules
        path: ./node_modules
        restore-key: ${{ github.sha }}-node-modules

    - name: Cache Package Manager
      if: steps.node-module-cache.outputs.cache-hit != 'true'
      id: package-manager-restore
      uses: actions/cache@v4.0.2
      with:
        key: ${{ github.sha }}-package-manager
        path: ~/.npm
        restore-key: ${{ github.sha }}-package-manager-restore

    - name: Install Packeage Manager
      if: steps.package-manager-restore.outputs.cache-hit != 'true' && steps.node-module-cache.outputs.cache-hit != 'true'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install Dependencies
      if: steps.node-module-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Test the app
      run: npm run test

